name = "cybermagnet-crm"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "cybermagnet-crm"
database_id = "96f365b2-8f1c-4a72-9d27-6d495113f179"
